### PR TITLE
Default to doing `apt-get update` during maintenance window

### LINKED ISSUE #14: Upgrade can fail if packages are updated between Monday and upgrade window
When packages are updated upstream between the time the image is built and the upgrade window, the upgrade can fail, as Ubuntu doesn't keep old packages in the repository.

Currently, we don't run `apt update` during the upgrade window to avoid having systems with different patchlevels depending on when in the week they're maintained.

## Steps to Reproduce the Problem

  1. Configure upgrade window late in the week (Thu/Fri)
  1. Enable upgrade
  1. Observe upgrade failing when Ubuntu packages have been updated throughout the week

## Actual Behavior
Upgrade fails with

```
2021-01-28 08:59:59 UTC [info] SUC - Populating apt package list on host 
2021-01-28 08:59:59 UTC [info] SUC - Get IP address of the push gateway 
2021-01-28 08:59:59 UTC [info] SUC - Found: 100.125.42.178:9091 
2021-01-28 08:59:59 UTC [info] SUC - Copy update script to host 
2021-01-28 09:00:00 UTC [info] SUC - Chrooting and update 
2021-01-28 09:00:00 UTC [info] SUC - Package upgrade version 0.0.1 
2021-01-28 09:00:00 UTC [info] SUC - Getting Linux distribution info based on /etc/os-release 
2021-01-28 09:00:00 UTC [info] SUC - Detected Ubuntu 18.04.5 LTS (Bionic Beaver) 
2021-01-28 09:00:00 UTC [info] SUC - Installing /usr/sbin/policy-rc.d 
2021-01-28 09:00:00 UTC [info] SUC - Doing package upgrade 
Reading package lists... 
Building dependency tree... 
Reading state information... 
Calculating upgrade... 
The following NEW packages will be installed: 
  linux-headers-4.15.0-134 linux-headers-4.15.0-134-generic 
  linux-image-4.15.0-134-generic linux-modules-4.15.0-134-generic 
The following packages will be upgraded: 
  linux-headers-generic linux-headers-virtual linux-image-virtual 
3 upgraded, 4 newly installed, 0 to remove and 0 not upgraded. 
Need to get 6892 B/33.2 MB of archives. 
After this operation, 164 MB of additional disk space will be used. 
Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-virtual amd64 4.15.0.134.121 
  404  Not Found [IP: 91.189.88.142 80] 
Err:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-generic amd64 4.15.0.134.121 
  404  Not Found [IP: 91.189.88.142 80] 
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-image-virtual amd64 4.15.0.134.121 
  404  Not Found [IP: 91.189.88.142 80] 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-headers-virtual_4.15.0.134.121_amd64.deb  404  Not Found [IP: 91.189.88.142 80] 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-headers-generic_4.15.0.134.121_amd64.deb  404  Not Found [IP: 91.189.88.142 80] 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux-meta/linux-image-virtual_4.15.0.134.121_amd64.deb  404  Not Found [IP: 91.189.88.142 80] 
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? 
2021-01-28 09:00:02 UTC [error] SUC - Package upgrade failed 
```

## Expected Behavior

Upgrade works without errors regardless of timing between the image build process and the upgrade window

## Potential solutions

Theres's several approaches that could mitigate this issue

1. Maintain an Ubuntu package mirror which is only synchronized once a week shortly before the SUC images are built
2. Unconditionally run `apt update` during the maintenance window, losing the patchlevel uniformity throughout the week
3. Optionally run `apt update` during the maintenance window (via argument to the upgrade script), if users don't care about patchlevel uniformity.

### PR DESCRIPTION
**Pull request by glrf**
We decided not to run Ubuntu package mirror and to live with losing the patchlevel uniformity throughout the week.

We now run `apt update` during the maintenance window by default. Users may disable this `apt update` with the `-p` flag.

Closes #14

### CODE REVIEW

File: scripts/run.sh [hunk 1]
```diff
@@ -5,10 +5,14 @@ set -e
 #shellcheck disable=SC1091
 . /scripts/functions.sh
 
-while getopts "us" opt; do
+while getopts "ups" opt; do
     case "${opt}" in
         u)
-            aptupdate=1
+            log warn "The flag '-u' is deprecated and script does apt-get update by default"
```
Comment (simu) [inline scripts/run.sh]:
```suggestion
            log warn "The flag '-u' is deprecated. The script does apt-get update by default. Use -p to use the package lists from the image."
```

**Review by simu — APPROVED** [review]
